In [50]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:95% !important;}
div.cell.code_cell.rendered{width:95%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:18pt;}
div.text_cell_render.rendered_html{font-size:16pt;}
div.output {font-size:22pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:22pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:22pt;padding:5px;}
table.dataframe{font-size:22px;}
</style>
"""))

<b><font size="7" color="red">ch09. 파일 i/o 프로그래밍</font></b>
- 파일 : txt, pickle(머신러닝모델저장, 배열저장), csv, json, h5(딥러닝모델저장)
## 1절 txt파일에 데이터저장하고 불러오기

In [51]:
# mode = 'r' 또는 'rt' : 텍스트 읽기모드로 열기. 파일이 없을 경우 예외 발생
# mode = 'w' 또는 'wt' : 텍스트 쓰기모드로 열기. 폴더가 없을 경우 예외 발생
                    # 파일이 없으면 생성. 파일이 있으면 덮어씀
# mode = 'a' 또는 'at' : 텍스트 쓰기모드로 열기. 폴더가 없을 경우 예외 발생
                    # 파일이 없으면 생성. 파일이 있으면 뒤에 append
f = open('data/ch09.txt', 'w') # encoding='cp949'(win)
print('쓰기 가능한지 :', f.writable())
f.write('Hello\nWorld\n')
f.close()

쓰기 가능한지 : True

In [52]:
# with구문을 사용면 매번 close()하는 코드가 불필요
with open('data/ch09.txt', 'wt') as f:
    print('쓰기 가능한지 :', f.writable())
    f.write('Python is easy.\nPython is smart.\n')

쓰기 가능한지 : True

In [53]:
with open('data/ch09.txt', 'a') as f: # cp949
    print('프린트 함수로 파일 쓰기가 가능합니다-파일출력', file=f)
    print('프린트 함수로 파일 쓰기가 가능합니다-콘솔출력')

프린트 함수로 파일 쓰기가 가능합니다-콘솔출력

- 한글 읽기/쓰기
    * cp949(한글완성형확장형) : open함수의 기본 인코딩(win)
    * utf-8(한글조합형) : 주피터노트북에서 열기

In [54]:
with open('data/ch09.txt', 'w', encoding='UTF-8') as f:
    # 방법1
    f.write('홍길동, 30, 서울\n')
    f.write('김길동, 20, 수원\n')
    # 방법2
    textlist = ['홍길동, 30, 서울\n', '김길동, 20, 부산\n']
    for line in textlist:
        f.write(line)
    # 방법3
    f.writelines(textlist) # 리스트를 한꺼번에 write

In [55]:
# 파일을 한꺼번에 읽어오기
with open('data/ch09.txt', 'rt', encoding='utf-8') as f:
    filecontent = f.read()
filecontent

'홍길동, 30, 서울\n김길동, 20, 수원\n홍길동, 30, 서울\n김길동, 20, 부산\n홍길동, 30, 서울\n김길동, 20, 부산\n'

In [56]:
# 파일을 한줄 읽고 출력하고, 한줄읽고 출력, ...
with open('data/ch09.txt', 'r', encoding='utf-8') as txtfile:
    line = txtfile.readline()
    while line != '':
        print(line, end='') # line에 \n이 포함되어 있어 출력시 개행은 제거
        line = txtfile.readline()

홍길동, 30, 서울
김길동, 20, 수원
홍길동, 30, 서울
김길동, 20, 부산
홍길동, 30, 서울
김길동, 20, 부산

In [57]:
# 파일을 한꺼번에 여러줄 읽어, 한줄씩 list담아 return
with open('data/ch09.txt', 'r', encoding='utf-8') as txtfile:
    lines = txtfile.readlines()
print(lines)

['홍길동, 30, 서울\n', '김길동, 20, 수원\n', '홍길동, 30, 서울\n', '김길동, 20, 부산\n', '홍길동, 30, 서울\n', '김길동, 20, 부산\n']

In [58]:
for line in lines:
    print(line, end='')

홍길동, 30, 서울
김길동, 20, 수원
홍길동, 30, 서울
김길동, 20, 부산
홍길동, 30, 서울
김길동, 20, 부산

# 2절 피클을 이용한 객체 저장 및 불러오기
- 머신러닝 모델저장, 배열저장, 객체저장
## 2.1 형식이 있는 텍스트 데이터 불러오기

In [59]:
with open('data/ch09_member.txt', 'r', encoding='UTF-8') as f:
    lines = f.readlines()
#print(lines)
for line in lines:
    # print(line)
    data = line.split(', ')
    # print(data)
    name = data[0]
    age = int(data[1])
    email = data[2]
    address = data[3].strip()
    print({'name':name,
           'age':age,
           'email':email,
           'address':address})

{'name': '홍길동', 'age': 20, 'email': 'kildong@hong.com', 'address': '서울시 관악구'}
{'name': '홍길숙', 'age': 25, 'email': 'kilsuk1@hong.com', 'address': '서울시 영등포구'}
{'name': '신길동', 'age': 30, 'email': 'shinkil@hong.com', 'address': '서울시 동작구'}

In [60]:
class Member:
    def __init__(self, name, age, email, address):
        self.name = name
        self.age  = age
        self.email = email
        self.address = address
    def __str__(self):
        return "{},{},{},{}".format(self.name, self.age, self.email, self.address)
#     def __eq__(self, other):
#         return self.name == other.name and \
#                 self.age == other.age and \
#                 self.email == other.email and \
#                 self.address == other.address
    def __eq__(self, other):
        return self.__str__() == other.__str__()
    def as_dict(self):
        '객체를 딕셔너리로 바꿔 return(json파일 저장시 필요)'
        return self.__dict__

In [61]:
member1 = Member("신길동", 30, 'shinkil@hong.com', '서울시 동작구')
member2 = Member("신길동", 30, 'shinkil@hong.com', '서울시 동작구')
print(member1.__str__())
print(member2)
print(member2==member1)
print(member2.__eq__(member1))
print(member1.__dict__)
print(member1.as_dict())

신길동,30,shinkil@hong.com,서울시 동작구
신길동,30,shinkil@hong.com,서울시 동작구
True
True
{'name': '신길동', 'age': 30, 'email': 'shinkil@hong.com', 'address': '서울시 동작구'}
{'name': '신길동', 'age': 30, 'email': 'shinkil@hong.com', 'address': '서울시 동작구'}

## 2.2 피클링
- 객체리스트 -> 피클파일로 쓰기
- 피클파일 -> 객체리스트로 읽기

In [62]:
# ch09_member.txt파일 -> 객체list, 딕셔너리list로 읽어오기
member_list = [] # Member객체 list
dict_list   = [] # 딕셔너리 list
with open('data/ch09_member.txt', 'r', encoding='UTF-8') as f:
    lines = f.readlines()
for line in lines:
    data = line.split(',')
    data = [item.strip() for item in data]
    name = data[0]
    age = int(data[1])
    email = data[2]
    address = data[3]
    member = Member(name, age, email, address)
    member_list.append(member)
    dict_list.append(member.__dict__)

In [63]:
for member in member_list: # 객체 list
    print(member)

홍길동,20,kildong@hong.com,서울시 관악구
홍길숙,25,kilsuk1@hong.com,서울시 영등포구
신길동,30,shinkil@hong.com,서울시 동작구

In [64]:
# 피클링(확장자 : pkl, pickle, data)을 이용한 객체를 파일에 저장하기
import pickle
with open('data/ch09_member.pkl', 'wb') as f:
    pickle.dump(member_list, f)

In [65]:
# 피클링을 이용한 파일을 객체리스트로 읽기
with open('data/ch09_member.pkl', 'rb') as f:
    load_member_list = pickle.load(f)

In [66]:
id(member_list), id(load_member_list)

(1351446195520, 1351444096768)

In [67]:
for idx in range(len(member_list)):
    print(idx, '번째 비교 :', (member_list[idx]==load_member_list[idx]))

0 번째 비교 : True
1 번째 비교 : True
2 번째 비교 : True

In [68]:
for idx,(member, load_member) in enumerate( zip(member_list, load_member_list)):
    print(idx , '번째 비교:', member==load_member)

0 번째 비교: True
1 번째 비교: True
2 번째 비교: True

In [69]:
result = [] #비교결과(True/False)를 append

In [70]:
for member, load_member in zip(member_list, load_member_list):
    result.append(member==load_member)
result

[True, True, True]

In [71]:
all(result) # 모든 요소들이 True인지 여부

True

In [72]:
all([True, True, True, True,False])

False

# 3절 CSV 파일 읽기/쓰기
- CSV파일의 자료를 리스트 데이터로 읽고 쓰기 (3.1과 3.2)
- CSV파일의 자료를 딕셔너리 데이터로 일고 쓰기 (3.3과 3.4
## 3.1 reader

In [73]:
import csv
with open('data/ch09_member1.csv', 'r', encoding='utf-8') as f:
    reader = csv.reader(f)
    result = list(reader)
result

[['홍길동', '20', 'kildong@hong.com', '서울시 관악구'],
 ['김길동', '40', 'kimdong@hong.com', '서울시 영등포구'],
 ['신길동', '30', 'sindong@hong.com', '서울시 동작구']]

In [74]:
with open('data/ch09_member1-cp.csv','r') as f:
    reader = csv.reader(f)
    for row in reader:
        print(row)

['홍길동', '20', 'kildong@hong.com', '서울시 관악구', '']
['김길동', '40', 'kimdong@hong.com', '서울시 영등포구', '팀장']
['신길동', '30', 'sindong@hong.com', '서울시 동작구', '']

In [75]:
# ""(따옴표)가 없는 데이터는 numeric으로
import csv
with open('data/ch09_member1.csv','r',encoding='utf-8') as f:
    reader = csv.reader(f,quoting = csv.QUOTE_NONNUMERIC)
    for row in reader:
        print(row)

['홍길동', 20.0, 'kildong@hong.com', '서울시 관악구']
['김길동', 40.0, 'kimdong@hong.com', '서울시 영등포구']
['신길동', 30.0, 'sindong@hong.com', '서울시 동작구']

## 3.2 writer
- list -> csv로 저장

In [76]:
user_list = [ ['신길동', 30, 'sindong@hong.com', '서울시 관악구'], 
             ['홍길동', 20, 'sindong@hong.com', '서울시 동작구'],
             ['박길동', 25, 'sindong@hong.com', '서울시 서초구'] ]

In [77]:
try:
    with open('data/ch09_member2-write.csv','w',newline='') as f:
        writer = csv.writer(f)
        
#         for user in user_list:
#             writer.writerow(user)
        
        writer.writerows(user_list)
except FileNotFoundError as e:
    print(e)

## 3.3 DictReader
- csv파일을 딕셔너리 데이터로 읽기

In [78]:
import csv
# header가 있는 csv파일을 딕셔너리로 읽기(ch09_member3.csv)
with open('data/ch09_member3.csv', 'r',encoding = 'utf-8') as f:
    dict_reader = csv.DictReader(f)
    result = list(dict_reader)
result

[{'name': '홍길동',
  'age': '20',
  'email': 'h@h.com',
  'address': '서울시 관악구',
  'job': None},
 {'name': '신길동',
  'age': '40',
  'email': 's@h.com',
  'address': '서울시 영등포구',
  'job': '팀장'},
 {'name': '김길동',
  'age': '30',
  'email': 'k@h.com',
  'address': '서울시 동작구',
  'job': None}]

In [123]:
# header가 있는 csv파일을 딕셔너리로 읽기(ch09_member3.csv)
with open('data/ch09_member3.csv', 'r',encoding = 'utf-8') as f:
    dict_reader = csv.DictReader(f)
    for row in dict_reader:
        print(row)

{'name': '홍길동', 'age': '20', 'email': 'h@h.com', 'address': '서울시 관악구', 'job': None}
{'name': '신길동', 'age': '40', 'email': 's@h.com', 'address': '서울시 영등포구', 'job': '팀장'}
{'name': '김길동', 'age': '30', 'email': 'k@h.com', 'address': '서울시 동작구', 'job': None}

In [124]:
#csv파일을 데이터프레임 데이터로 읽기
import pandas as pd
members = pd.read_csv('data/ch09_member3.csv') # 기본 인코딩 방식이 encoding='utf-8'
members

  name  age    email   address  job
0  홍길동   20  h@h.com   서울시 관악구  NaN
1  신길동   40  s@h.com  서울시 영등포구   팀장
2  김길동   30  k@h.com   서울시 동작구  NaN

In [125]:
type(members)

pandas.core.frame.DataFrame

In [126]:
pd.DataFrame(data=result)

       0
0   True
1   True
2   True
3  False
4   True

In [127]:
# header 가 없는 csv파일을 딕셔너리 데이터로 읽기(ch09_member1-cp.csv)
with open('data/ch09_member1-cp.csv','r') as f:
    dict_reader = csv.DictReader(f, fieldnames=['Name','Age','Email','Address','Job'])
    for row in dict_reader:
        print(row)

{'Name': '홍길동', 'Age': '20', 'Email': 'kildong@hong.com', 'Address': '서울시 관악구', 'Job': ''}
{'Name': '김길동', 'Age': '40', 'Email': 'kimdong@hong.com', 'Address': '서울시 영등포구', 'Job': '팀장'}
{'Name': '신길동', 'Age': '30', 'Email': 'sindong@hong.com', 'Address': '서울시 동작구', 'Job': ''}

## 3.4 DictWriter
- 딕셔너리 데이터(딕셔너리 list)를csv파일로 쓰기

In [128]:
user1 ={'Name': '신길동', 'Age': '30', 'Email': 'sindong@hong.com', 'Address': '서울'}
user2 ={'Name': '홍길동', 'Age': '20', 'Email': 'jindong@hong.com', 'Address': '관악'}
user3 ={'Name': '김길동', 'Age': '10', 'Email': 'kindong@hong.com', 'Address': '안양'}
user_list = [user1, user2, user3]
user_list

[{'Name': '신길동', 'Age': '30', 'Email': 'sindong@hong.com', 'Address': '서울'},
 {'Name': '홍길동', 'Age': '20', 'Email': 'jindong@hong.com', 'Address': '관악'},
 {'Name': '김길동', 'Age': '10', 'Email': 'kindong@hong.com', 'Address': '안양'}]

In [129]:
fieldnames = list(user1.keys())
fieldnames

['Name', 'Age', 'Email', 'Address']

In [130]:
with open('data/ch09_member4.csv','w', encoding='utf-8',newline='') as f:
    dict_writer = csv.DictWriter(f, fieldnames = fieldnames)
    dict_writer.writeheader() # header 한줄 쓰기
#        for user in user_list:
#            dict_writer.writerows(user_list)
    dict_writer.writerows(user_list)

# 4절 JSON 파일에 저장하고 불러오기(dump, load)
```
[{'title':'국가정보원 화제', 'url':'http://~', 'content':'무시기무시기~'},
{'title':'국가정보원 화제', 'url':'http://~', 'content':'무시기무시기~'},
{'title':'국가정보원 화제', 'url':'http://~', 'content':'무시기무시기~'},}
```
## 4.1 JSON dump(파일에 저장)
### (1) 딕셔너리 list를 json파일로 저장
### (2) 객체 list를 json파일로 저장(객체를 딕셔너리로 바꾸는 함수가 필요)

In [131]:
data = [{'name': '홍길동', 'age': '20', 'email': 'h@h.com', 'address': '서울'},
       {'name': '신길동', 'age': '22', 'email': 'P@h.com', 'address': '부산'},
       {'name': '김길동', 'age': '24', 'email': 'S@h.com', 'address': '관악'}]
data

[{'name': '홍길동', 'age': '20', 'email': 'h@h.com', 'address': '서울'},
 {'name': '신길동', 'age': '22', 'email': 'P@h.com', 'address': '부산'},
 {'name': '김길동', 'age': '24', 'email': 'S@h.com', 'address': '관악'}]

In [132]:
# ensure_ascii 옵션의 역할 : ASCII 코드를 넘어선 문자를 어떻게 처리할지
# 기본값(True) : ASCII 코드 범위를 넘어선 글자는 유니코드로 저장
# False : 비ASCII 문자는 원래 형태로 그대로 저장
import json
with open('data/ch09_member1.json', 'w') as jsonfile:
    json.dump(data, # 딕셔너리 리스트
             jsonfile, # 파일 스트림
             ensure_ascii=False, # 비ASCII 코드 문자 처리 여부
             indent='  ') # 들여쓰기 여부

### 2. 객체 list를 json파일로 저장

In [133]:
class Member:
    def __init__(self, name, age, email, address):
        self.name = name
        self.age  = age
        self.email = email
        self.address = address
    def __str__(self):
        return "{},{},{},{}".format(self.name, self.age, self.email, self.address)
    def as_dict(self):
        '객체를 딕셔너리로 바꿔 return(json파일 저장시 필요)'
        return self.__dict__

In [134]:
member_list = [Member('홍길동',30,'h@h.com','서울'),
              Member('마길동',25,'m@h.com','하남'),
              Member('박길동',35,'p@p.com','대전')]
[member.__str__() for member in member_list]

['홍길동,30,h@h.com,서울', '마길동,25,m@h.com,하남', '박길동,35,p@p.com,대전']

In [135]:
with open('data/ch09_member2.json','w',encoding ='utf-8') as jsonfile:
    json.dump(member_list,# 저장할 리스트(객체 리스트)
             jsonfile,
             ensure_ascii=False,
             indent ='\t',
             default =Member.as_dict)

## 4.2 JSON load(파일 읽기)
### (1) json파일을 딕셔너리 리스트로 읽기
### (2) json파일을 객체 리스트로 읽기(딕셔너리를 객체로 return 하는 함수가 필요)

In [136]:
### (1) json파일을 딕셔너리 리스트로 읽기
with open('data/ch09_member1.json', 'r') as jsonfile:
    load_data = json.load(jsonfile)
load_data

[{'name': '홍길동', 'age': '20', 'email': 'h@h.com', 'address': '서울'},
 {'name': '신길동', 'age': '22', 'email': 'P@h.com', 'address': '부산'},
 {'name': '김길동', 'age': '24', 'email': 'S@h.com', 'address': '관악'}]

In [137]:
type(load_data),type(load_data[0])

(list, dict)

In [138]:
### (2) json파일을 객체 리스트로 읽기(딕셔너리를 객체로 return 하는 함수가 필요)
# {'name': '홍길동', 'age': '20', 'email': 'h@h.com', 'address': '서울'} => Member('홍',3,'h@h','설')
def as_member(dic):
    #return Member(dic['name'],dic['age'],dic['email'],dic['address'])
    return Member(dic.get('name'),dic.get('age'),dic.get('email'),dic.get('address'))

In [139]:
with open('data/ch09_member2.json', 'r', encoding='utf-8') as jsonfile:
    load_member_list = json.load(jsonfile, 
                                 object_hook=as_member) # 딕셔너리를 객체로 return 함수
for load_member in load_member_list:
    print(load_member)

홍길동,30,h@h.com,서울
마길동,25,m@h.com,하남
박길동,35,p@p.com,대전

In [140]:
# member_list => ch09_member2.json = > Load_member_list
# member_list와 load_member_list가 같은 내용인지 검사

In [141]:
result = []

for member, load_member in zip(member_list,load_member_list):
    result.append(member == load_member)
print('두 객체 리스트의 모든 데이터가 일치한느지 여부 :',all(result))

두 객체 리스트의 모든 데이터가 일치한느지 여부 : False

In [144]:
# False인 곳의 index가 궁금?
import numpy as np

result = np.array([True, True, True, False, True])
np.where(result == False)

(array([3], dtype=int64),)

In [146]:
result = set() # 빈 셋 / {}:빈딕셔너리
for member, laod_member in zip(member_list, load_member_list):
    result.add(member == load_member)
result

{False}