In [7]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:19pt;}
div.text_cell_render.rendered_html{font-size:16pt;}
div.output {font-size:16pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:16pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:16pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<b><font size="7" color="red">ch14. 웹데이터 수집</font></b>
# 1절. BEAUTIFULSOUP과 parser
'pip install bs4' 아나콘다를 설치하면 자동 설치되는 패키지 7500개에 포함

- 공식 Documentation : https://beautiful-soup-4.readthedocs.io/en/latest/

In [8]:
# 내 Local PC의 파일을 url(http://~)처럼 접근
import requests # http 요청 처리하는 Lib
from requests_file import FileAdapter # file://프로토콜을 다루기 위함

In [12]:
s = requests.Session() # HTTP 요청처리하는 세션 객체
s.mount("file://", FileAdapter())
# file://경로로 들어오면 이 요청은 c:(로컬파일)을 접근
response = s.get('file:///ai/ch14_sample.html')
response

In [13]:
if response:
    print('잘 접근하였습니다.')
else:
    print('접근을 못했습니다')

잘 접근하였습니다.

In [14]:
response.status_code
    # 200 : 정상
    # 404 : 없는페이지
    # 406 : get, post 오류

200

In [15]:
response.content # 바이너리 형식의 html

b'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90 \xec\x95\x88\xec\x9d\x98 \xeb\x82\xb4\xec\x9a\xa9</div>\r\n  <p>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90\xec\x84\x9c \xed\x99\x9c\xec\x9a\xa9\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</p>\r\n  <div class="contents">\r\n    \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\xa5\xbc \xec\x96\xb4\xeb\x96\xbb\xea\xb2\x8c \xec\x9e\x91\xec\x84\xb1\xed\x95\x98\xeb\x8a\x90\xeb\x83\x90\xec\x97\x90 \xeb\x94\xb0\xeb\x9d\xbc\r\n    <span>\xeb\x8b\xa4\xeb\xa5\xb8<b>\xec\x9a\x94\xec\x86\x8c\xea\xb0\x80 \xeb\xb0\x98\xed\x99\x98</b></span>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4\r\n  </div>\r\n  <div>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90 <b>\xed\x99\x9c\xec\x9a\xa9</b>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</div>\r\n</body>\r\n</html>'

In [16]:
response.content.decode('utf-8')

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [17]:
response.text # HTML파일의 텍스트 내용

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [20]:
# html 파싱
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.content, #response.text
                    "html.parser")
# soup

In [27]:
# soup.select_one('선택자') : 해당선택자 처음 하나만
el = soup.select_one('h1') # 처음 나오는 h1태그 하나만
print('el :', el)
print('el.text :', el.text)
print('el.string :', el.string)
print('el의 속성들 :', el.attrs)
print('el의 id속성 :', el.attrs['id']) # el.attrs은 딕셔너리
print('el의 id속성 :', el.attrs.get('id'))
print('el의 href속성 :', el.attrs.get('href'))
print('el의 태그이름 :', el.name)

el : <h1 class="greeting css" id="text">Hello, CSS</h1>
el.text : Hello, CSS
el.string : Hello, CSS
el의 속성들 : {'class': ['greeting', 'css'], 'id': 'text'}
el의 id속성 : text
el의 id속성 : text
el의 href속성 : None

In [32]:
# soup.select('선택자') : 해당 선택자 모두
els = soup.select('h1') # h1태그를 list
print('els :', els)
print('els의 text들 :', [el.text for el in els])
print('els의 string들 :', [el.string for el in els])
print('els의 속성들 :', [el.attrs for el in els])
print('els의 class 속성들 :', [el.attrs.get('class') for el in els])

els : [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]
els의 text들 : ['Hello, CSS', 'Hi, CSS']
els의 string들 : ['Hello, CSS', 'Hi, CSS']
els의 속성들 : [{'class': ['greeting', 'css'], 'id': 'text'}, {'class': ['css']}]
els의 class 속성들 : [['greeting', 'css'], ['css']]

In [33]:
# soup.find(태그, 속성) : soup.select_one('선택자')와 유사
print('select_one :', soup.select_one('h1.css') )
print('find :', soup.find('h1', {'class':'css'}) ) # soup.select_one('h1.css')
print('find :', soup.find('h1', class_='css') )
print()
print('select_one :', soup.select_one('h1#text') )
print('find :', soup.find('h1', {'id':'text'}))

find : <h1 class="greeting css" id="text">Hello, CSS</h1>

In [36]:
# soup.find_all(태그, 속성) : soup.select('선택자')와 유사
print('select :', soup.select('h1.css'))
print('find_all :', soup.find_all('h1', class_='css'))
print('find_all :', soup.find_all('h1', {'class':'css'}))

select : [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>, <span>다른<b>요소가 반환</b></span>]
find_all : [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]

In [37]:
print('select :', soup.select('h1.css, span'))
print('find_all :', soup.find_all(['h1', 'span'], {'class':'css'}))
print('find_all :', soup.find_all('h1', class_='css') + \
                     soup.find_all('span'))

select : [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>, <span>다른<b>요소가 반환</b></span>]
find_all : [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]
find_all : [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>, <span>다른<b>요소가 반환</b></span>]

In [38]:
# 없는 엘리먼트 찾기
print('select(빈 list) :', soup.select('a.css'))
print('select_one(None) :', soup.select_one('a.css'))
print('find_all(빈 list) :', soup.find_all('a', {'class','css'}))
print('find(None) :', soup.find('a', {'class':'css'}))

select(빈 list) : []
select_one(None) : None
find_all(빈 list) : []
find(None) : None

# 2절. 정적 웹 데이터 수집(정적 웹크롤링)
## 2.1 BeautifulSoup을 활용한 html 웹 데이터수집
### 1) 환율정보 가져오기 (네이버증권 -> 시장지표_)
-https://finance.naver.com/marketindex/

In [39]:
# 크롤링 허용범위는 사이트마다 ~/robots.txt에서 확인
    # Allow : / - 사이트의 모든 경로(/)애ㅔ 대한 크롤링 허용

In [43]:
# 방법1
import requests
from bs4 import BeautifulSoup
url = 'https://finance.naver.com/marketindex/'
response = requests.get(url)
#response.status_code
# response.text / response.content.decode('cp949')
soup = BeautifulSoup(response.text, "html.parser")

In [49]:
# 방법2
from urllib.request import urlopen
url = 'https://finance.naver.com/marketindex/'
response = urlopen(url)
response.status
# response.read() / responseread().decode('cp949')
soup = BeautifulSoup(response, "html.parser")

In [57]:
# div.head_info > span.value (find함수)
prices = []
headinfos = soup.find_all('div', class_='head_info')
for headinfo in headinfos:
    price = headinfo.find('span', class_ = 'value')
    #print(price.text.repalce(',', ''))
    prices.append(float(''.join(price.text.split(','))))
print(prices)

[1454.5, 945.19, 1681.33, 204.2, 153.42, 1.1564, 1.3161, 99.47, 59.75, 1698.27, 4009.8, 189125.23]

In [73]:
# div.head_info > span.value (select함수)
prices = soup.select('div.head_info > span.value')
print([float(p.text.replace(',','')) for p in prices])

[1454.5, 945.19, 1681.33, 204.2, 153.42, 1.1564, 1.3161, 99.47, 59.75, 1698.27, 4009.8, 189125.23]

In [61]:
titles = soup.select('h3.h_lst > span.blind')
for t in titles:
    print(t.text, end='\t')

미국 USD	일본 JPY(100엔)	유럽연합 EUR	중국 CNY	달러/일본 엔	유로/달러	영국 파운드/달러	달러인덱스	WTI	휘발유	국제 금	국내 금

In [65]:
units = soup.select('div.head_info > span > span.blind')
units = [unit.text for unit in units]
units.insert(7, '') # 7번째에 '' 추가
units

['원', '원', '원', '원', '엔', '달러', '달러', '', '달러', '원', '달러', '원']

In [68]:
statuses = soup.select('div.head_info > span.blind')
for idx in range(len(statuses)):
    print(statuses[idx].text, end='\t')

하락	하락	하락	하락	상승	하락	상승	하락	상승	상승	상승	상승

In [69]:
len(titles), len(prices), len(units), len(statuses)

(12, 0, 12, 12)

In [74]:
for idx in range(len(titles)):
    print("{} : {}{} - {}".format(titles[idx].text,
                                 prices[idx].text,
                                 units[idx],
                                 statuses[idx].text))

미국 USD : 1,454.50원 - 하락
일본 JPY(100엔) : 945.19원 - 하락
유럽연합 EUR : 1,681.33원 - 하락
중국 CNY : 204.20원 - 하락
달러/일본 엔 : 153.4200엔 - 상승
유로/달러 : 1.1564달러 - 하락
영국 파운드/달러 : 1.3161달러 - 상승
달러인덱스 : 99.4700 - 하락
WTI : 59.75달러 - 상승
휘발유 : 1698.27원 - 상승
국제 금 : 4009.8달러 - 상승
국내 금 : 189125.23원 - 상승

In [79]:
for title, price, unit, status in zip(titles, prices, units, statuses):
    print("{} : {}{} -{}".format(title.text,
                                price.text,
                                unit,
                                status.text))

미국 USD : 1,454.50원 -하락
일본 JPY(100엔) : 945.19원 -하락
유럽연합 EUR : 1,681.33원 -하락
중국 CNY : 204.20원 -하락
달러/일본 엔 : 153.4200엔 -상승
유로/달러 : 1.1564달러 -하락
영국 파운드/달러 : 1.3161달러 -상승
달러인덱스 : 99.4700 -하락
WTI : 59.75달러 -상승
휘발유 : 1698.27원 -상승
국제 금 : 4009.8달러 -상승
국내 금 : 189125.23원 -상승

### 2) 이번주 로또 번호 출력
- https://dhlottery.co.kr/gameResult.do?method=byWin (google에 로또번호 당첨번호 검색)
````
11997회(2025년 11월 08일 추첨)
당첨번호 [1,5,7,26,28,43]
보너스 30
````

In [107]:
# 방법1
import requests
from bs4 import BeautifulSoup
url = 'https://dhlottery.co.kr/gameResult.do?method=byWin'
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")
#soup

In [108]:
# 방법2
from urllib.request import urlopen
url = 'https://dhlottery.co.kr/gameResult.do?method=byWin'
response = urlopen(url)
response.status
soup = BeautifulSoup(response, "html.parser")
# soup

In [109]:
times = soup.select_one('div.win_result strong').text
date  = soup.select_one('div.win_result > p.desc').text
# date = soup.find('p', class_='desc').text
lotto_number_el = soup.select('div.num.win  span')
lotto_number = [int(el.text) for el in lotto_number_el]
bonus_number = int(soup.select_one('div.num.bonus > p > span').text)

In [110]:
print(times, date)
print('당첨번호 ',lotto_number)
print('보 너 스 ', bonus_number)

1197회 (2025년 11월 08일 추첨)
당첨번호  [1, 5, 7, 26, 28, 43]
보 너 스  30

### 3) 다음 검색 리스트
```
no title   href
0 "한풀 꺾인 비트코인 https://daum.net/v/202511110094711892
```

In [135]:
# 방법1
import requests
from bs4 import BeautifulSoup
word = '비트코인'
url = 'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q='+word
print(url)
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

items_find_list = [] #검색한 결과를 담을 리스트
items_el = soup.select('div.item-title > strong.tit-g > a')
for idx, item in enumerate(items_el):
    #print(idx, item.text, item.attrs.get('href'))
    items_find_list.append({'no':idx,
                           'title':item.text,
                           'link':item.attrs.get('href')})
import pandas as pd

pd.DataFrame(items_find_list)

https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=비트코인

,no,title,link
0,0,"""한풀 꺾인 비트코인, 상승세 곧 회복""…근거는?",http://v.daum.net/v/20251110094711892
1,1,비트코인 1억5500만원대 소폭 상승…트럼프 발언탓?,http://v.daum.net/v/20251110092814031
2,2,"美 셧다운 종료 기대…비트코인, 10만 5000달러 회복[코인브리핑]",http://v.daum.net/v/20251110111435519
3,3,“지금 들어가?”… 트럼프 관세 배당 발언에 10만달러 회복한 비트코인,http://v.daum.net/v/20251110114112103
4,4,"""비트코인 21억 간다더니""...갑자기 말 바꿨다",http://v.daum.net/v/20251109105545139
5,5,"트럼프 돈 푼다...비트코인, 관세 배당금에 반등 [매일코인]",http://v.daum.net/v/20251110112101913
6,6,"비트코인, 트럼프 ‘2000달러 지급’ 발언에 10만4000달러선 [크립토브리핑]",http://v.daum.net/v/20251110103033108
7,7,"“비트코인 약세, 닷컴버블과 판박이”…큰손·장투족 매일 던진다",http://v.daum.net/v/20251110094507791
8,8,비트코인 '와르르' 내려오는데 '의외'의 전망,http://v.daum.net/v/20251107210115339
9,9,"[가상자산 나침반] ‘겹악재’ 비트코인, 반전 포인트 나올까",http://v.daum.net/v/20251109112746909

In [137]:
# 방법2 : 불가
from urllib.request import urlopen
from urllib.parse import quote
word = quote('비트코인') # url에 한글이 포함된 경우 한글을 quote()로 변환
url = 'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q='+word
print(url)
response = urlopen(url)

import pandas as pd

https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8

In [141]:
items_find_list = [] #검색한 결과를 담을 리스트
items_el = soup.select('div.item-title > strong.tit-g > a')
for idx, item in enumerate(items_el):
    items_find_list.append([idx, item.text, item.attrs['href']])
pd.DataFrame(items_find_list, columns=['번호','제목','링크'])

,번호,제목,링크
0,0,"""한풀 꺾인 비트코인, 상승세 곧 회복""…근거는?",http://v.daum.net/v/20251110094711892
1,1,비트코인 1억5500만원대 소폭 상승…트럼프 발언탓?,http://v.daum.net/v/20251110092814031
2,2,"美 셧다운 종료 기대…비트코인, 10만 5000달러 회복[코인브리핑]",http://v.daum.net/v/20251110111435519
3,3,“지금 들어가?”… 트럼프 관세 배당 발언에 10만달러 회복한 비트코인,http://v.daum.net/v/20251110114112103
4,4,"""비트코인 21억 간다더니""...갑자기 말 바꿨다",http://v.daum.net/v/20251109105545139
5,5,"트럼프 돈 푼다...비트코인, 관세 배당금에 반등 [매일코인]",http://v.daum.net/v/20251110112101913
6,6,"비트코인, 트럼프 ‘2000달러 지급’ 발언에 10만4000달러선 [크립토브리핑]",http://v.daum.net/v/20251110103033108
7,7,"“비트코인 약세, 닷컴버블과 판박이”…큰손·장투족 매일 던진다",http://v.daum.net/v/20251110094507791
8,8,비트코인 '와르르' 내려오는데 '의외'의 전망,http://v.daum.net/v/20251107210115339
9,9,"[가상자산 나침반] ‘겹악재’ 비트코인, 반전 포인트 나올까",http://v.daum.net/v/20251109112746909

In [148]:

items_find_list = [] # 검색한 결과를 담을 리스트
# div.item-title > strong.tit-g > a
item_titles = soup.find_all('div', class_='item-title')
for idx, item in enumerate(item_titles):
    a = item.find('a')
    #print(idx, a.text, a.attrs['href'])
    #items_find_list.append([idx, a.text, a.attrs['href']])
    items_find_list.append({
        'no':idx,
        'title':a.text,
        'link':a.attrs['href'],
    })
pd.DataFrame(items_find_list)

,no,title,link
0,0,"""한풀 꺾인 비트코인, 상승세 곧 회복""…근거는?",http://v.daum.net/v/20251110094711892
1,1,비트코인 1억5500만원대 소폭 상승…트럼프 발언탓?,http://v.daum.net/v/20251110092814031
2,2,"美 셧다운 종료 기대…비트코인, 10만 5000달러 회복[코인브리핑]",http://v.daum.net/v/20251110111435519
3,3,“지금 들어가?”… 트럼프 관세 배당 발언에 10만달러 회복한 비트코인,http://v.daum.net/v/20251110114112103
4,4,"""비트코인 21억 간다더니""...갑자기 말 바꿨다",http://v.daum.net/v/20251109105545139
5,5,"트럼프 돈 푼다...비트코인, 관세 배당금에 반등 [매일코인]",http://v.daum.net/v/20251110112101913
6,6,"비트코인, 트럼프 ‘2000달러 지급’ 발언에 10만4000달러선 [크립토브리핑]",http://v.daum.net/v/20251110103033108
7,7,"“비트코인 약세, 닷컴버블과 판박이”…큰손·장투족 매일 던진다",http://v.daum.net/v/20251110094507791
8,8,비트코인 '와르르' 내려오는데 '의외'의 전망,http://v.daum.net/v/20251107210115339
9,9,"[가상자산 나침반] ‘겹악재’ 비트코인, 반전 포인트 나올까",http://v.daum.net/v/20251109112746909

In [185]:
# 다음 뉴스 검색(원하는 키워드를 원하는 페이지를 가져오기)
import requests
from bs4 import BeautifulSoup
import pandas as pd
def collect_news_list(keyword, page):
    'keyword로 page에 다음 뉴스검색한 결과를 출력->list를 return'
    #url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q={keyword}&p={page}'
    # response = requests.get(url)
    url = f'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8'
    params = {'q':keyword, 'p':page}
    response = requests.get(url, params=params)
    soup = BeautifulSoup(response.text, 'html.parser')
    items_find_list = [] # 검색한 결과를 담는 리스트
    item_titles = soup.select('div.item-title > strong.tit-g > a')
    print(keyword)
    for idx, item in enumerate(item_titles):
        items_find_list.append([(page-1)*10+idx, item.text, item.attrs['href']])
    return items_find_list

In [186]:
collect_news_list('비트코인', 3)

비트코인

[[20,
  ' 돈나무 언니, 비트코인 전망 낮췄다...“150만→120만달러" ',
  'http://v.daum.net/v/20251107110438971'],
 [21,
  ' 연구소서 실험하려 샀는데…비트코인 1000배 대박 터졌다 ',
  'http://v.daum.net/v/20251109120511705'],
 [22,
  ' "비트코인 \'1000배 잭팟\' 터뜨렸어요"···실험용으로 97개 샀다가 \'횡재\' 맞은 \'이 나라\' ',
  'http://v.daum.net/v/20251109075014647'],
 [23,
  ' 돈나무 언니도 생각 바꿨다…비트코인 강세전망 20%↓ ',
  'http://v.daum.net/v/20251107040000760'],
 [24,
  ' JP모건 "비트코인, 금 비해 저평가...공정가치 17만 달러" ',
  'http://v.daum.net/v/20251107092549359'],
 [25,
  " 연구용으로 산 비트코인 97개…13년만에 1000배 수익 '잭팟' ",
  'http://v.daum.net/v/20251109113613079'],
 [26, ' 비트코인 이달 7% 추락에도…"金보다 저평가" ', 'http://v.daum.net/v/20251107173448660'],
 [27,
  ' “주식보다 더 떨어져”…휘청이는 비트코인 “분위기 반전 어렵다” ',
  'http://v.daum.net/v/20251106171049044'],
 [28, ' 한때 10만弗 붕괴, 날개 꺾인 비트코인 ', 'http://v.daum.net/v/20251106041647056'],
 [29,
  ' “곡소리 들리네” 비트코인·이더리움 붕괴…위험자산 ‘회피 심리’ ',
  'http://v.daum.net/v/20251105080314455']]

In [190]:
import time
keywords = ['청바지','동대문']
result0 = [] # 청바지 1~3페이지까지 검색한 결과를 담을 list
result1 = [] # 동대문 1~3페이지까지 검색한 결괄르 담을 list
pages = 3
for i, keyword in enumerate(keywords):
    print(f'==={i+1}번쨰 검색어 {keyword} 검색 결과 수집 중입니다===')
    for page in range(1, pages+1):
        if i==0:
            result0.extend(collect_news_list(keyword,page))
        elif i == 1:
            result1.extend(collect_news_list(keyword,page))
        time.sleep(0.5)

===1번쨰 검색어 청바지 검색 결과 수집 중입니다===
청바지
청바지
청바지
===2번쨰 검색어 동대문 검색 결과 수집 중입니다===
동대문
동대문
동대문

In [189]:
result0_df = pd.DataFrame(result0, columns=['no','title','link'])
result1_df = pd.DataFrame(result1, columns=['no','title','link'])
result1_df.head()

,no,title,link
0,0,"“돈 벌어가세요” 동대문 일요시장, 겨울옷 핫플된 사연? [르포]",http://v.daum.net/v/20251110100357735
1,1,"동대문구, ‘11월 자전거교실’ 개강… 올해 마지막 초보자 교육 진행",http://v.daum.net/v/20251110145114101
2,2,"음주운전 차, 동대문역서 인도 돌진...日 관광객 '사망'",http://v.daum.net/v/20251103073316480
3,3,"동대문구, 25일까지 '주민 건강도시학교'···""건강하게 살자""",http://v.daum.net/v/20251109223318356
4,4,"서울 동대문구, 15일 배봉산정원 가족축제 개최",http://v.daum.net/v/20251104104517122

In [195]:
result0_df.to_csv('data/ch14_{keywords{0}}.csv',index=False, encoding='cp949')
result1_df.to_csv('data/ch14_{keywords{1}}.csv',index=False)

### 4) User-Agent를 추가하여 크롤링
- 자동으로 브라어저를 통해 요청하는 것 처럼 보이기

In [203]:
# 방법2 :
from urllib.request import urlopen, Request
from urllib.parse import quote
word = quote('비트코인') # 한글을 encoding 처리
url = 'https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q='+word
print(url)
# headers = {'User-Agent':
#           'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36'}
# request = Request(url, headers = headers)
request = Request(url)
request.add_header('User-Agent',
                  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36')
response = urlopen(request)
soup = BeautifulSoup(response, 'html.parser')
# soup

https://search.daum.net/search?w=news&nil_search=btn&DA=PGD&enc=utf8&cluster=y&cluster_page=1&q=%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8

###4)

In [209]:
# 방법 1
import requests
url = 'https://www.melon.com/chart/hot100/index.htm'
melonpage = requests.get(url)
melonpage
soup = BeautifulSoup(melonpage.text, 'html.parser')
soup

In [218]:
# 방법2
from urllib.request import urlopen, Request
url = 'https://www.melon.com/chart/hot100/index.htm'
# melonpage = urlopen(url) # 에러남
headers = {'user-agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36'}
request = Request(url, headers=headers)
melonpage = urlopen(request)
soup = BeautifulSoup(melonpage, 'html.parser')
#soup

In [233]:
# 방법1 : User-Agent 추가
url = 'https://www.melon.com/chart/hot100/index.htm'

headers = {'user-agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36'}

melonpage  = requests.get(url, headers=headers)
soup = BeautifulSoup(melonpage.text, # melponpage.content
                    'html.parser')
ranks = soup.select('td div.wrap.t_center > span.rank')

titles = soup.select('div.ellipsis.rank01 > span')

singers = soup.select('div.ellipsis.rank02 > span')

#[singer.text.strip()[:20] for singer in singers]

for rank, title, singer in zip(ranks, titles, singers):
    print(f'{rank.text}위 | {title.text.strip()} - {singer.text.strip()[:20]}')

1위 | Blue Valentine - NMIXX
2위 | 타임캡슐 - 다비치
3위 | SPAGHETTI (feat. j-hope of BTS) - LE SSERAFIM (르세라핌),
4위 | Good Goodbye - 화사 (HWASA)
5위 | 달리 표현할 수 없어요 - 로이킴
6위 | IRIS OUT - Kenshi Yonezu
7위 | 시작의 아이 ❍ - 박다혜, 마크툽 (MAKTUB)
8위 | XOXZ - IVE (아이브)
9위 | Hollywood Action - BOYNEXTDOOR
10위 | Rich Man - aespa
11위 | 한번 더 이별 - 이창섭
12위 | body - 다영 (DAYOUNG)
13위 | FOCUS - Hearts2Hearts (하츠투하츠
14위 | 순간을 영원처럼 - 임영웅
15위 | 들꽃이 될게요 - 임영웅
16위 | 가만히 눈을 감고 - DK(디셈버)
17위 | 그댈 위한 멜로디 - 임영웅
18위 | 비가 와서 - 임영웅
19위 | JANE DOE - Kenshi Yonezu, Hikar
20위 | Be My Light - 이세계아이돌
21위 | 답장을 보낸지 - 임영웅
22위 | OVERDRIVE - TWS (투어스)
23위 | 바이, 썸머 - 아이유
24위 | 알겠어요 미안해요 - 임영웅
25위 | ULSSIGU - 임영웅
26위 | Nameless - 이세계아이돌
27위 | 꿈의 버스 - DAY6 (데이식스)
28위 | Wonderful Life - 임영웅
29위 | 돌아보지 마세요 - 임영웅
30위 | 나는야 HERO - 임영웅
31위 | 우리에게 안녕 - 임영웅
32위 | 있잖아 - BOYNEXTDOOR
33위 | Stargazers - 이세계아이돌
34위 | ELEVATE - 이세계아이돌
35위 | MEMORY - 이세계아이돌
36위 | 나였으면 - 나윤권, 도경수(D.O.)
37위 | 당신을 위하여 - 이보람 (씨야)
38위 | 숨바꼭질 (Hide and Seek) - PLAVE
39위 | 0+0 - 한로로
40위 | GO! - CORTIS (코르티스)
41위 | INSIDE OUT - DAY6 (데이식스)
42위 | WE GO UP - BABYMONSTER
43위 | BURNING UP - MEOVV (미야오)
44위 | Live In Paris - BOYNEXTDOOR
45위 | 끝사랑 - 권진아
46위 | 사랑만 해두자 - 경서
47위 | Talk to You - 연준
48위 | Mamma Mia - izna (이즈나)
49위 | 주르르 - 이창섭
50위 | Bathroom - BOYNEXTDOOR
51위 | Pretty Please - Hearts2Hearts (하츠투하츠
52위 | 어떻게 사랑이 그래요 - 최은빈
53위 | 그대가 분다 - HYNN (박혜원)
54위 | 딱 1년만 (Feat. 10CM) - BIG Naughty (서동현)
55위 | JAM! - BOYNEXTDOOR
56위 | Surf - NCT WISH
57위 | SPINNIN′ ON IT - NMIXX
58위 | 밤하늘의 별을(더 리슨 5) - 허각, 켄(KEN), 권진아, ASH
59위 | I'll Never Love Again - WOODZ
60위 | Let Me Tell You (feat. Daniela of KATSEYE) - 연준, Daniela
61위 | Coma - 연준
62위 | Forever - 연준
63위 | FaSHioN - CORTIS (코르티스)
64위 | blue - yung kai
65위 | DANCING ALONE - KiiiKiii (키키)
66위 | 지나왔던 추억이 사랑이 되고 - 이무진
67위 | To Me From Me (Prod. TABLO) - KiiiKiii (키키)
68위 | Nothin’ ’Bout Me - 연준
69위 | Do It - 연준
70위 | Ruin My Life - BOYNEXTDOOR
71위 | 오늘은 왠지 - 이찬원
72위 | number one rockstar - 다영 (DAYOUNG)
73위 | 내게 남은 사랑을 드릴께요 - 최유리
74위 | 비라도 내렸으면 좋겠어 - 폴킴
75위 | 있어줘요 - 허각
76위 | Stay - 어반자카파
77위 | 시월의 시 - 이찬원
78위 | 나의 오랜 여행 - 이찬원
79위 | COLOR - NCT WISH
80위 | SAY CHEESE! - BOYNEXTDOOR
81위 | 바이 바이 (Feat. 이무진) - BIG Naughty (서동현)
82위 | 시간을 넘어 너에게로 - 도영 (DOYOUNG)
83위 | CYNICAL - 선미
84위 | 첫사랑은 안녕히- - 잔나비
85위 | 첫사랑 - 이찬원
86위 | 가위바위보 - FIFTY FIFTY
87위 | 해야 뜨지 말아 줘 - DAY6 (데이식스)
88위 | 처음 불러보는 노래 - KickFlip(킥플립)
89위 | 낙엽처럼 떨어진 너와 나 - 이찬원
90위 | 우리들의 순간 - 브라운 아이드 소울
91위 | 엄마의 봄날 - 이찬원
92위 | 빛나는 별 - 이찬원
93위 | 락앤롤 인생 - 이찬원
94위 | 5, 4, 3 (Pretty woman) (feat. Lay Bankz) - 에스쿱스X민규 (SEVENTEEN)
95위 | 나를 떠나지 마요 - 이찬원
96위 | 말했잖아 - 이찬원
97위 | 하루 - 수지 (Suzy)
98위 | 숙녀에게 - 최유리
99위 | Falling (Feat. Young K (DAY6)) - WOODZ
100위 | Love on the canvas - 소희 (SOHEE)

### 5) 네이버 지식인으로 검색(open API 사용X)
- 특정 keyword를 특정페이지 수만큼

In [9]:

# 방법1
from requests import get
from bs4 import BeautifulSoup
keyword = '쳇지피티'
# url = 'https://kin.naver.com/search/list.naver'
# params = {'query' : keyword}
# response = get(url, params=params)
url = f'https://kin.naver.com/search/list.naver?query={keyword}'
response = get(url)
print(response.status_code)
soup = BeautifulSoup(response.text, 'html.parser')
# soup

200

In [10]:
# 방법2
from urllib.request import urlopen
from urllib.parse import quote
keyword = quote('쳇지피티')
url = f'https://kin.naver.com/search/list.naver?query={keyword}'
print(url)
response = urlopen(url)
print(response.status)
soup = BeautifulSoup(response, 'html.parser')
#soup

https://kin.naver.com/search/list.naver?query=%EC%B3%87%EC%A7%80%ED%94%BC%ED%8B%B0
200

In [43]:

# 페이징 포함
from urllib.request import urlopen
from urllib.parse import quote
from bs4 import BeautifulSoup
import pandas as pd
keyword = quote('쳇지피티')
pages = 3
items_list = [] # 크롤링한 데이터를 담을 list(title, link)
for page in range(1, pages+1):
    url = f'https://kin.naver.com/search/list.naver?query={keyword}&page={page}'
    response = urlopen(url)
    # print(response.status)
    soup = BeautifulSoup(response, 'html.parser')
    items = soup.select('dt > a')
    for item in items:
        title = item.text
        link  = item.attrs.get('href')
        items_list.append({
            'title': title,
            'link' : link
        })
df = pd.DataFrame(items_list)
print(df.shape)
print(df.loc[29, 'link'])
df.sample()

(30, 2)
https://kin.naver.com/qna/detail.naver?d1id=3&dirId=31301&docId=485933293&qb=7LOH7KeA7ZS87Yuw&enc=utf8

      title                                               link
24  쳇지피티 댓글  https://kin.naver.com/qna/detail.naver?d1id=8&...

## 2.2 openAPI사용 : json 웹데이터 수집
### 1) 네이버 지식인으로 검색(open API 사용 O)
- 네이버 개발자센터에서 애플리케이션 등록(이름/검색/WEB설정http://localhost)
- .env파일에 CLIEnt_ID/CLIENT_SECRET 환경변수 저장
- 환경변수를 읽기 위해서 `pip install dotenv`
- 특정 keyword를 지식검색(데이터수 30개)

In [19]:
%pip install dotenv

Collecting dotenv
  Downloading dotenv-0.9.9-py2.py3-none-any.whl (1.9 kB)
Collecting python-dotenv
  Downloading python_dotenv-1.2.1-py3-none-any.whl (21 kB)
Installing collected packages: python-dotenv, dotenv
Successfully installed dotenv-0.9.9 python-dotenv-1.2.1
Note: you may need to restart the kernel to use updated packages.

In [5]:
# 환경변수 읽어오기
from dotenv import load_dotenv
import os
load_dotenv(
    #dotenv_path='.env'
           )# 현 소스와 같은 폴더내의 .env를 메모리에 Load

#print(os.getenv('CLIENT_ID'))
#print(os.getenv('CLIENT_SECRET'))

True

In [30]:
#방법2
import os
import urllib.request
import json
client_id = os.getenv('CLIENT_ID')
client_secret = os.getenv('CLIENT_SECRET')
encText = urllib.parse.quote("쳇지피티")
url = "https://openapi.naver.com/v1/search/kin?query=" + encText # JSON 결과
# request = urllib.request.Request(url)
# request.add_header("X-Naver-Client-Id",client_id)
# request.add_header("X-Naver-Client-Secret",client_secret)
headers = {
    'X-Naver-Client-Id':client_id,
    'X-Naver-Client-Secret':client_secret
}
request = urllib.request.Request(url, headers=headers)
response = urllib.request.urlopen(request)
rescode = response.status
if(rescode==200):
    response_body = response.read()
    print(type(response_body.decode('utf-8')))
    print(response_body.decode('utf-8')[:50])
else:
    print("Error Code:" + rescode)
items = json.loads(response_body.decode('utf-8'))['items']
items_list = []
for item in items:
    title = item['title'].replace('<b>','').replace('</b>','')
    link  = item.get('link')
    description = item.get('description').replace('<b>','').replace('</b>','')
    items_list.append([title, link, description])
pd.DataFrame(items_list, columns=['title', 'link', 'description']).head()

<class 'str'>
{
	"lastBuildDate":"Tue, 11 Nov 2025 12:33:26 +090

,title,link,description
0,쳇지피티 사주 정확성,https://kin.naver.com/qna/detail.naver?d1id=3&...,쳇지피티 사주 정확성 몇프로 정도 될까요? 큰틀은 얼추 맞는거 같기도하고 모르겠네요...
1,쳇지피티 관해서,https://kin.naver.com/qna/detail.naver?d1id=1&...,쳇지피티한테 질문 제대로 하려면 어떻게 해야 하냐요?... 쳇지피티 한테 하는질문도...
2,사주에서 뭐가 부족한지 봐주세요(쳇지피티 답변 금지),https://kin.naver.com/qna/detail.naver?d1id=3&...,사주에서 뭐가 부족한지 봐주세요(쳇지피티 답변 금지) 남매입니다 남자 1986년 9...
3,쳇지피티 유료로 전환시,https://kin.naver.com/qna/detail.naver?d1id=1&...,쳇지피티 무료버전으로 카톡대화창 전송해서 상대의심리에 관한 분석요청을 많이했는데 첨...
4,쳇지피티 3일 리셋,https://kin.naver.com/qna/detail.naver?d1id=8&...,... 쳇지피티 어떻게 하는건가욤 유료결제인가요 유료결제는 얼마인가요 그거 하게되면...

In [33]:
# 방법1
import requests
import pandas as pd
import json # response텍스트를 json스타일의 딕셔너리로
client_id = os.getenv('CLIENT_ID')
client_secret = os.getenv('CLIENT_SECRET')
query = '쳇지피티'
headers = {
    'X-Naver-Client-Id':client_id,
    'X-Naver-Client-Secret':client_secret
}
# url = f'https://openapi.naver.com/v1/search/kin?query={query}&display=30'
# response = requests.get(url, headers=headers)
url = 'https://openapi.naver.com/v1/search/kin'
params = {'query':query, 'display':30}
response = requests.get(url, params=params, headers=headers)
# print(response.text[:500])
# items = json.loads(response.text)['items']
items = response.json()['items']
items_list = []
for item in items:
    title = item['title'].replace('<b>','').replace('</b>','')
    link  = item.get('link')
    description = item.get('description').replace('<b>','').replace('</b>','')
    items_list.append([title, link, description])
pd.DataFrame(items_list, columns=['title', 'link', 'description']).head()

,title,link,description
0,쳇지피티 사주 정확성,https://kin.naver.com/qna/detail.naver?d1id=3&...,쳇지피티 사주 정확성 몇프로 정도 될까요? 큰틀은 얼추 맞는거 같기도하고 모르겠네요...
1,쳇지피티 관해서,https://kin.naver.com/qna/detail.naver?d1id=1&...,쳇지피티한테 질문 제대로 하려면 어떻게 해야 하냐요?... 쳇지피티 한테 하는질문도...
2,사주에서 뭐가 부족한지 봐주세요(쳇지피티 답변 금지),https://kin.naver.com/qna/detail.naver?d1id=3&...,사주에서 뭐가 부족한지 봐주세요(쳇지피티 답변 금지) 남매입니다 남자 1986년 9...
3,쳇지피티 유료로 전환시,https://kin.naver.com/qna/detail.naver?d1id=1&...,쳇지피티 무료버전으로 카톡대화창 전송해서 상대의심리에 관한 분석요청을 많이했는데 첨...
4,쳇지피티 3일 리셋,https://kin.naver.com/qna/detail.naver?d1id=8&...,... 쳇지피티 어떻게 하는건가욤 유료결제인가요 유료결제는 얼마인가요 그거 하게되면...

### quiz) 네이버 open API를 이용해서 청바지 이미지 100건의 데이터를 ch14_청바지.csv출력
```
    제목,링크,썸네일,sizeheight,sizewidth
```

In [80]:
ef get_image_list(query):
    'query로 검색한 이미지 정보(정보,링크,썸네일,크기) 100건 데이터 프레임을 return(방법2)'
    from urllib.request import urlopen, Request
    from urllib.parse import quote
    import json
    import pandas as pd
    from dotenv import load_dotenv
    import os
    load_dotenv()
    client_id = os.getenv('CLIENT_ID')
    client_secret = os.getenv('CLIENT_SECRET')
    encText = quote(query)
    url = f'https://openapi.naver.com/v1/search/image?query={encText}&display=100'
    headers = {
        'X-Naver-Client-Id':client_id,
        'X-Naver-Client-Secret':client_secret
    }
    request = Request(url, headers=headers)
    response = urlopen(request)
    # print(response.read().decode('utf-8'))
    items = json.loads(response.read().decode('utf-8'))['items']
    items_list = [] # 정보가 담길 리스트
    for item in enumerate(items):
        #print(item)
        link = item.get('link')
        thumbnail = item.get('thumbnail')
        items_list.append({
            '제목':item.get('title'),
            '링크':link,
            '썸네일': thumbnail,
            'sizeheight': int(item.get('sizeheight')),
            'sizewidth':  int(item.get('sizewidth')),
        })
        # 이미지 파일 저장
        save_image('메일', idx, link, query)
        save_image('썸네일', idx, thumbnail, query)
        if (idx%20 == 0) & (idx!=0):
            print(f'= = = {idx}% 진행완료 = = =')
    return pd.DataFrame(items_list)
df = get_image_list_save_image("청바지")
df.to_csv('image/ch14_청바지.csv')
df.sample()

SyntaxError: invalid syntax (3440439115.py, line 1)

In [86]:

def get_image_list(query):
    'query로 검색한 이미지 정보(정보,링크,썸네일,크기) 100건 데이터 프레임을 return(방법1)'
    import requests
    import json
    import pandas as pd
    from dotenv import load_dotenv
    import os
    load_dotenv()
    client_id = os.getenv('CLIENT_ID')
    client_secret = os.getenv('CLIENT_SECRET')
    url = 'https://openapi.naver.com/v1/search/image'
    params = {'query':query, 'display':100 }
    headers = {
        'X-Naver-Client-Id':client_id,
        'X-Naver-Client-Secret':client_secret
    }
    response = requests.get(url, params=params, headers=headers)
    #items = response.json()['items']
    items = json.loads(response.text)['items']
    items_list = []
    for item in items:
        #print(item)
        link = item.get('link')
        thumbnail = item.get('thumbnail')
        items_list.append({
            '제목':item.get('title'),
            '링크':link,
            '썸네일': thumbnail,
            'sizeheight': int(item.get('sizeheight')),
            'sizewidth':  int(item.get('sizewidth')),
        })
        
    return pd.DataFrame(items_list)
df = get_image_list("청바지")
df.to_csv('data/ch14_청바지.csv')
df.sample()

,제목,링크,썸네일,sizeheight,sizewidth
64,여아 초등학생 롱 와이드 단추 밴딩 청바지 | 돈버는 쇼핑 도매꾹 [도매꾹] 여아 ...,https://rorane.godohosting.com/pants/button_je...,https://search.pstatic.net/sunny/?type=b150&sr...,831,800

In [78]:
print(df.loc[99, '링크'])
print(df.loc[99, '썸네일'])

http://shop1.phinf.naver.net/20251012_221/1760195026829GJCj4_JPEG/94327887959887005_1382895326.jpeg
https://search.pstatic.net/common/?type=b150&src=http://shop1.phinf.naver.net/20251012_221/1760195026829GJCj4_JPEG/94327887959887005_1382895326.jpeg

In [83]:

def save_image(attr, idx, link, query):
    'link의 이미지를 image/attr_idx_query.확장자로 local에 저장'
    import requests
    file_extension = link.split('.')[-1] # 확장자
    quote_index = file_extension.find('?') # 확장자뒤에 ?가 있는 위치 .jpg?w=780
    if quote_index != -1:
        file_extension = file_extension[:quote_index]
    img = requests.get(link).content # 바이너리
    with open(f'image/{attr}_{idx+1:02}_{query}.{file_extension}', 'wb') as f:
        f.write(img)
save_image('메인', 0, df.loc[25, '링크'], '청바지')

In [84]:
def get_image_list_save_image(query):
    'query로 검색한 이미지 정보(정보,링크,썸네일,크기) 100건 데이터 프레임을 return(방법1)'
    import requests
    import json
    import pandas as pd
    from dotenv import load_dotenv
    import os
    load_dotenv()
    client_id = os.getenv('CLIENT_ID')
    client_secret = os.getenv('CLIENT_SECRET')
    url = 'https://openapi.naver.com/v1/search/image'
    params = {'query':query, 'display':100 }
    headers = {
        'X-Naver-Client-Id':client_id,
        'X-Naver-Client-Secret':client_secret
    }
    response = requests.get(url, params=params, headers=headers)
    #items = response.json()['items']
    items = json.loads(response.text)['items']
    items_list = [] # 정보가 담길 리스트
    for idx, item in enumerate(items):
        link = item.get('link')
        thumbnail = item.get('thumbnail')
        items_list.append({
            '제목':item.get('title'),
            '링크':link,
            '썸네일': thumbnail,
            'sizeheight': int(item.get('sizeheight')),
            'sizewidth':  int(item.get('sizewidth')),
        })
        # 이미지 파일 저장
        save_image('메인', idx, link, query)
        save_image('썸네일', idx, thumbnail, query)
        if (idx%20 == 0) & (idx!=0):
            print(f'= = = {idx}% 진행중 = = =')
    print('= = = 완료 = = =')
    return pd.DataFrame(items_list)
df = get_image_list_save_image("청바지")
df.to_csv('image/ch14_청바지.csv')
df.sample()

= = = 20% 진행중 = = =
= = = 40% 진행중 = = =
= = = 60% 진행중 = = =
= = = 80% 진행중 = = =
= = = 완료 = = =

,제목,링크,썸네일,sizeheight,sizewidth
91,남자연청바지 흑청바지 : 웨어 라운드,https://shop-phinf.pstatic.net/20250522_11/174...,https://search.pstatic.net/common/?type=b150&s...,1000,1000

## 2.3 XML 웹데이터 수집
- RSS /open API 을 통한 XML 웹데이터 수집

### 1) 전국 날씨 RSS를 BeautifulSoup을 이용한 크롤링

In [9]:
import requests
from urllib.request import urlopen
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
items_list = []
url = 'https://www.kma.go.kr/repositary/xml/fct/mon/img/fct_mon1rss_108_20251106.xml'
# 방법1
# target = requests.get(url)
# soup = BeautifulSoup(target.text, "xml") # pip install lxml 필요없음
# 방법2
target = urlopen(url)
soup = BeautifulSoup(target, "xml")
local_tas = soup.select('local_ta')
for local_ta in local_tas:
    local_name = local_ta.select_one('local_ta_name').text
    week1_normalYear = local_ta.select_one('week1_local_ta_normalYear').text
    week1_similarRange = local_ta.select_one('week1_local_ta_similarRange').text
    week1_minVal = local_ta.select_one('week1_local_ta_minVal').text
    week1_similarVal = local_ta.select_one('week1_local_ta_similarVal').text
    week1_maxVal = local_ta.select_one('week1_local_ta_maxVal').text
    items_list.append({
        '지역':local_name,
        '1주평년기온':week1_normalYear,
        '1주기온범위':week1_similarRange,
        '1주낮을확률':week1_minVal,
        '1주비슷할확률':week1_similarVal,
        '1주높을확률':week1_maxVal
    })
df = pd.DataFrame(items_list)
df['1주평년기온'] = df['1주평년기온'].astype(np.float64)
df['1주낮을확률'] = df['1주낮을확률'].astype(np.int16)
df['1주비슷할확률'] = df['1주비슷할확률'].astype(np.int16)
df['1주높을확률'] = df['1주높을확률'].astype(np.int16)
df.head()

               지역  1주평년기온   1주기온범위  1주낮을확률  1주비슷할확률  1주높을확률
0   전국(제주도,북한제외)      5.9  5.0~6.8      20       40      40
1      서울ㆍ인천ㆍ경기도      4.8  3.7~5.9      20       40      40
2         강원도 영서      2.6  1.5~3.7      20       40      40
3         강원도 영동      5.8  4.9~6.7      20       40      40
4     대전ㆍ세종ㆍ충청남도      5.4  4.5~6.3      20       40      40

### 2) XML응답하는 open API 활용
- data.go.kr에서
    - 서울특별시_노선정보조회 서비스(버스ID, 정류장목록과정류장ID)
    - 서울특별시_버스위치정보조회 서비스(실시간 버스 위치 목록)

In [ ]:
# STEP 1 버스번호의 버스 id받아오기
# 서울특별시_노선정보조회 서비스 - 3번 기능(getBusRouteList) 이용

In [2]:
from dotenv import load_dotenv
import os 
load_dotenv()
# print(os.getenv('KEY1'))

True

In [11]:
import requests
from bs4 import BeautifulSoup
# urlretrive(url, 저장경로) : url의 파일을 저장경로에 저장
from urllib.request import urlretrieve
from urllib.parse import quote
#busNum = quote('종로07')
busNum = '162'
key = os.getenv('KEY1')
url = f'http://ws.bus.go.kr/api/rest/busRouteInfo/getBusRouteList?ServiceKey={key}&strSrch={busNum}'
print(url)
savefilename1 = 'data/ch14_busInfo.xml'
urlretrieve(url, savefilename1) #xml파일(url)을 savafilename으로 저장
with open(savefilename1, encoding='utf-8') as f:
    xml = f.read();
soup = BeautifulSoup(xml, 'xml')

http://ws.bus.go.kr/api/rest/busRouteInfo/getBusRouteList?ServiceKey=ZS3iEVZ82iG9dvZc3urYq03YK9x0dwPWsaXcaNd1XACv8yWys1TONILRRSHiRNyrFo1qVk379RdHIUhAtRaL5w%3D%3D&strSrch=162

In [18]:
import requests 
from urllib.parse import quote
busNum = '162'
key = os.getenv('KEY1')
url = f'http://ws.bus.go.kr/api/rest/busRouteInfo/getBusRouteList?ServiceKey={key}&strSrch={busNum}'
response = requests.get(url)

soup = BeautifulSoup(response.text, 'xml')
for item in soup.select('itemList'):
    busRouteNm = item.select_one('busRouteNm').text
    if busRouteNm == busNum:
        busRouteId = item.select_one('busRouteId').text
        print(busRouteId)
        break;
print('busRouteId =', busRouteId)

100100034
busRouteId = 100100034

In [ ]:
# stpe2. 버스id로 버스정류장목록받아오기(정류장명, 정류장id, 경도, 위도)
# 서울특별시_노선정보조회 서비스 - 4번기능()

In [25]:
import pandas as pd
url2 = f'http://ws.bus.go.kr/api/rest/busRouteInfo/getStaionByRoute?ServiceKey={key}&busRouteId={busRouteId}'
response = requests.get(url2)
soup = BeautifulSoup(response.content,'xml')
itemLists = soup.find_all('itemList')
print(f'{busNum}번 정류장 갯수 : {len(itemLists)}')

bus_station = []
for itemList in itemLists:
    stationNm = itemList.find('stationNm').text # 정류소 이름
    station   = itemList.find('station').text # 정류소 id
    gpsX      = itemList.find('gpsX').text # 경도
    gpsY      = itemList.find('gpsY').text # 위도
    bus_station.append([stationNm, station, gpsX, gpsY])
df_station = pd.DataFrame(bus_station, columns=['정류소명','id','경도','위도'])
df_station.head()

162번 정류장 갯수 : 77

             정류소명         id              경도             위도
0         정릉산장아파트  107000071      127.003343      37.616712
1    정릉4동주민센터.경국사  107000073      127.006345      37.613529
2     북한산보국문역2번출구  107000518  127.0079858233   37.612293899
3  성북청수도서관.정릉4동성당  107000075  127.0084193769  37.6115696748
4          정릉시장입구  107000077  127.0098212542  37.6084653256

In [ ]:
# step3. 버스 id로 실시간위치정보를 받아오기(차량번호, 혼잡도, 최종정류장id,다음정류장id, 도착소요시간)
# 서울특별시_버스위치정보조회 서비스 - 2번(getBusPosByRtidList)

In [36]:
url3 = f'http://ws.bus.go.kr/api/rest/buspos/getBusPosByRtid?serviceKey={key}&busRouteId={busRouteId}'
# print(url3)
response = requests.get(url3)
soup = BeautifulSoup(response.text, 'xml')
itemLists = soup.select('itemList')
print(f'운행중인 버스는 {len(itemLists)}대입니다')
bus_position = []
for itemList in itemLists:
    plainNo = itemList.select_one('plainNo').text # 차량번호
    congetion = itemList.select_one('congetion').text # 혼잡도(congetion)
    # 0 : 없음, 3 : 여유, 4 : 보통, 5 : 혼잡, 6 : 매우혼잡
    congetion = '없음' if congetion=='0' \
            else '여유' if congetion=='3' \
            else '보통' if congetion=='4' \
            else '혼잡' if congetion=='5' else '매우혼잡'
    bus_position.append({
        '차량번호':plainNo,
        '혼잡도':congetion
    })
df_position = pd.DataFrame(bus_position)
df_position

운행중인 버스는 22대입니다

         차량번호 혼잡도
0   서울70사6560  여유
1   서울74사3360  여유
2   서울74사1625  여유
3   서울74사2218  여유
4   서울74사2216  여유
5   서울70사6558  보통
6   서울74사1638  여유
7   서울74사1536  보통
8   서울74사2244  여유
9   서울74사3381  여유
10  서울70사6549  여유
11  서울74사2201  여유
12  서울74사1967  보통
13  서울70사6556  보통
14  서울74사1537  보통
15  서울74사1618  여유
16  서울74사3372  여유
17  서울75사2805  여유
18  서울70사6557  여유
19  서울74사1604  혼잡
20  서울74사3366  여유
21  서울74사2296  여유